### ISSUE TITLE
how to convert Unicode ->Zawgyi on oc?

### ISSUE THREAD

**Issue by cccey** [saturngod/Zawgyi-To-Unicode-iOS#1]
@saturngod i found Unicode ->Zawgyi on swift, but i not found it on oc,  please help me!

**Comment by saturngod** [comment]
please use Rabbit

Objective-C

https://github.com/Rabbit-Converter/Rabbit/tree/master/source/output/objective-c

Swift

https://github.com/Rabbit-Converter/Rabbit/tree/master/source/output/swift3
